### ISSUE TITLE
Could not find module "@angular-devkit/build-angular"

### ISSUE THREAD

**Issue by papaiatis** [xieziyu/angular2-draggable#126]
I added angular2-draggable to my project with
`npm install angular2-draggable --save`
However, after install, my project does not build anymore, because:
```
Could not find module "@angular-devkit/build-angular" from "/home/dev/frontend".
Error: Could not find module "@angular-devkit/build-angular" from "/home/dev/frontend".
    at Object.resolve (/home/dev/frontend/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/home/dev/frontend/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/home/dev/frontend/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/dev/frontend/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:30:22)
    at /home/dev/frontend/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:99:19
    at new Promise (<anonymous>)
    at Observable.toPromise (/home/dev/frontend/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:97:16)
    at ServeCommand.initialize (/home/dev/frontend/node_modules/@angular/cli/models/architect-command.js:91:94)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
```
I saw that `@angukar-devkit/build-angular` is a dev dependency of `angular2-draggable` so I added `"@angular-devkit/build-angular": "~0.6.8",` to my `devDependencies` list.
After that I could build the project again, but even though I **did not add this module** to my app, I'm getting this error in the javascript console:
`Uncaught Error: Can't resolve all parameters for ApplicationModule: (?).`
Then I tried importing this module as it was described in the documentation, but I'm still getting the same javascript error.
I'm on Angular 7.0.4

Any idea how to fix this?

**Comment by papaiatis** [comment]
I managed to fix it by updating the devkit module
from: 
`"@angular-devkit/build-angular": "~0.6.8"`
to:
`"@angular-devkit/build-angular": "~0.11.0"`
